export const EMOJI_CATEGORIES = [
    {
        name: "表情",
        emojis: [
            { char: "😃", label: "哈哈" },
            { char: "😄", label: "大笑" },
            { char: "😁", label: "嘻嘻" },
            { char: "😆", label: "大笑" },
            { char: "😅", label: "苦笑" },
            { char: "😂", label: "笑哭" },
            { char: "🤣", label: "狂笑" },
            { char: "😊", label: "微笑" },
            { char: "😇", label: "天使笑" },
            { char: "🙂", label: "轻笑" },
            { char: "🙃", label: "倒置笑" },
            { char: "😉", label: "眨眼" },
            { char: "😌", label: "安心" },
            { char: "😍", label: "花痴" },
            { char: "🥰", label: "喜笑颜开" },
            { char: "😘", label: "飞吻" },
            { char: "😗", label: "亲亲" },
            { char: "😚", label: "闭眼亲" },
            { char: "😋", label: "好吃" },
            { char: "😛", label: "吐舌" },
            { char: "😝", label: "眯眼吐舌" },
            { char: "😜", label: "眨眼吐舌" },
            { char: "🤪", label: "滑稽" },
            { char: "🤨", label: "挑眉" },
            { char: "🧐", label: "单片眼镜" },
            { char: "🤓", label: "书呆子" },
            { char: "😎", label: "酷" },
            { char: "🤩", label: "星星眼" },
            { char: "🥳", label: "庆祝" },
            { char: "🤐", label: "闭嘴" },
            { char: "😑", label: "无语" },
            { char: "🙄", label: "翻白眼" },
            { char: "😪", label: "困" },
            { char: "🤤", label: "流口水" },
            { char: "😴", label: "睡觉" },
            { char: "🤮", label: "呕吐" },
            { char: "🥶", label: "冷脸" },
            { char: "🤡", label: "小丑" },
            { char: "🤕", label: "受伤" },
            { char: "😮", label: "吃惊" },
            { char: "🥺", label: "可怜" },
            { char: "😨", label: "害怕" },
            { char: "😡", label: "怒火中烧" },
            { char: "😈", label: "恶魔微笑" },
            { char: "💩", label: "大便" },
            { char: "👻", label: "鬼" },
        ]
    },
    {
        name: "手势",
        emojis: [
            { char: "👍", label: "点赞" },
            { char: "👎", label: "点踩" },
            { char: "👊", label: "拳头" },
            { char: "✊", label: "握拳" },
            { char: "🤛", label: "左拳" },
            { char: "🤜", label: "右拳" },
            { char: "🤞", label: "手指交叉" },
            { char: "✌️", label: "剪刀手" },
            { char: "🤟", label: "我爱你" },
            { char: "🤘", label: "摇滚" },
            { char: "🤙", label: "打电话" },
            { char: "👌", label: "OK" },
            { char: "🤏", label: "小一点" },
            { char: "👈", label: "向左" },
            { char: "👉", label: "向右" },
            { char: "👆", label: "向上" },
            { char: "👇", label: "向下" },
            { char: "☝️", label: "提示" },
            { char: "👋", label: "挥手" },
            { char: "🤚", label: "举手" },
            { char: "🖐️", label: "张开手掌" },
            { char: "✋", label: "停止" },
            { char: "🖖", label: "瓦肯礼" },
            { char: "👏", label: "鼓掌" },
            { char: "🙌", label: "举双手" },
            { char: "🤲", label: "捧手" },
            { char: "🤝", label: "握手" },
            { char: "🙏", label: "合十" }
        ]
    },
    {
        name: "物品",
        emojis: [
            { char: "📱", label: "手机" },
            { char: "💻", label: "笔记本" },
            { char: "⌨️", label: "键盘" },
            { char: "🖥️", label: "显示器" },
            { char: "🖨️", label: "打印机" },
            { char: "🖱️", label: "鼠标" },
            { char: "🖲️", label: "轨迹球" },
            { char: "🕹️", label: "手柄" },
            { char: "🗜️", label: "夹具" },
            { char: "💾", label: "软盘" },
            { char: "💿", label: "光盘" },
            { char: "📀", label: "DVD" },
            { char: "📼", label: "录像带" },
            { char: "📷", label: "相机" },
            { char: "📸", label: "拍照" },
            { char: "📹", label: "摄像机" },
            { char: "🎥", label: "电影机" },
            { char: "📽️", label: "放映机" },
            { char: "💡", label: "灯泡" },
            { char: "🔦", label: "手电" },
            { char: "🕯️", label: "蜡烛" },
            { char: "🔋", label: "电池" },
            { char: "🔌", label: "电源插头" }
        ]
    },
    {
        name: "食物",
        emojis: [
            { char: "🍎", label: "红苹果" },
            { char: "🍐", label: "梨" },
            { char: "🍊", label: "橙子" },
            { char: "🍋", label: "柠檬" },
            { char: "🍌", label: "香蕉" },
            { char: "🍉", label: "西瓜" },
            { char: "🍇", label: "葡萄" },
            { char: "🍓", label: "草莓" },
            { char: "🍈", label: "甜瓜" },
            { char: "🍒", label: "樱桃" },
            { char: "🍑", label: "桃子" },
            { char: "🥭", label: "芒果" },
            { char: "🍍", label: "菠萝" },
            { char: "🥥", label: "椰子" },
            { char: "🥝", label: "奇异果" },
            { char: "🍅", label: "番茄" },
            { char: "🍆", label: "茄子" },
            { char: "🥑", label: "牛油果" },
            { char: "🥦", label: "西兰花" },
            { char: "🥬", label: "生菜" },
            { char: "🥒", label: "黄瓜" },
            { char: "🌶️", label: "辣椒" },
            { char: "🌽", label: "玉米" },
            { char: "🥕", label: "胡萝卜" },
            { char: "🥔", label: "土豆" }
        ]
    },
    {
        name: "动物",
        emojis: [
            { char: "🐶", label: "狗" },
            { char: "🐱", label: "猫" },
            { char: "🐭", label: "鼠" },
            { char: "🐹", label: "仓鼠" },
            { char: "🐰", label: "兔子" },
            { char: "🦊", label: "狐狸" },
            { char: "🐻", label: "熊" },
            { char: "🐼", label: "熊猫" },
            { char: "🐨", label: "考拉" },
            { char: "🐯", label: "老虎" },
            { char: "🦁", label: "狮子" },
            { char: "🐮", label: "牛" },
            { char: "🐷", label: "猪" },
            { char: "🐽", label: "猪鼻" },
            { char: "🐸", label: "青蛙" },
            { char: "🐵", label: "猴子" },
            { char: "🙈", label: "不看" },
            { char: "🙉", label: "不听" },
            { char: "🙊", label: "不说" },
            { char: "🐒", label: "猴" },
            { char: "🐔", label: "鸡" },
            { char: "🐧", label: "企鹅" },
            { char: "🐦", label: "鸟" },
            { char: "🐤", label: "小鸡" },
            { char: "🐣", label: "破壳" }
        ]
    }
];

